export const AllServices = [
	{
		id: 1,
		type: "Appliance",
		split: true,
		description:
			"Comprehensive air conditioner service for split and window units, ensuring peak performance and comfort year-round.",
		name: "Air Conditioner",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "Split",
				description: [
					{
						name: "Service",
						price: "500",
						imgSrc: "/assests/ac1.jpg",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/ac2.png",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "1500",
						imgSrc: "/assests/ac3.jpg",
					},
					{
						name: "Uninstallation",
						price: "500",
						imgSrc: "/assests/ac4.png",
					},
				],
			},
			{
				name: "Window",
				description: [
					{
						name: "Service",
						price: "400",
						imgSrc: "/assests/wa1.jpg",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/wa2.jpg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "600",
						imgSrc: "/assests/windowACInstallation.jpg",
					},
					{
						name: "Uninstallation",
						price: "300",
						imgSrc: "/assests/wa4.jpg",
					},
				],
			},
		],
	},
	{
		id: 2,
		type: "Appliance",
		split: true,
		description:
			"Expert repair, installation, and maintenance services for residential and commercial RO water purifiers, ensuring pure and safe drinking water.",

		name: "RO Water Purifier",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "Residential RO",
				description: [
					{
						name: "Service",
						price: "350",
						imgSrc: "/assests/wp1.png",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/wp2.jpg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "400",
						imgSrc: "/assests/wp3.png",
					},
					{
						name: "Uninstallation",
						price: "200",
						imgSrc: "/assests/wp4.png",
					},
				],
			},
			{
				name: "Commercial RO",
				description: [
					{
						name: "Service",
						price: "500",
						imgSrc: "/assests/ro1.png",
					},
					{
						name: "Repair",
						price: "400",
						imgSrc: "/assests/ro2.png",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "600",
						imgSrc: "/assests/ro3.jpg",
					},
					{
						name: "Uninstallation",
						price: "300",
						imgSrc: "/assests/ro4.png",
					},
				],
			},
		],
	},
	{
		id: 3,
		type: "Appliance",
		split: true,
		description:
			"Comprehensive service encompassing repair, installation, and Uninstallation for semi-automatic, top-load, and front-load washing machines, ensuring seamless laundry solutions for every household.",

		name: "Washing Machine",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "Top Load and Front Load",
				description: [
					{
						name: "Service",
						price: "500",
						imgSrc: "/assests/front1.jpg",
					},
					{
						name: "Repair",
						price: "350",
						imgSrc: "/assests/top.jpg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "600",
						imgSrc: "/assests/wm3.jpg",
					},
					{
						name: "Uninstallation",
						price: "300",
						imgSrc: "/assests/wm4.jpg",
					},
				],
			},
			{
				name: "Semi-Automatic",
				description: [
					{
						name: "Service",
						price: "300",
						imgSrc: "/assests/semi1.jpg",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/Repair.jpg",
						extra: "Excluding Spare Parts",
					},
				],
			},
		],
	},
	{
		id: 4,
		type: "Appliance",
		split: true,
		description:
			"Complete LED service solutions including repair, installation, and Uninstallation for screens up to 32 inches and above, ensuring optimal viewing experiences for all sizes.",

		name: "LED",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "UPTO 32 Inches",
				description: [
					{
						name: "Service",
						price: "300",
						imgSrc: "/assests/LED.png",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/led1.jpg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "500",
						imgSrc: "/assests/led2.jpg",
					},
					{
						name: "Uninstallation",
						price: "300",
						imgSrc: "/assests/led4.jpg",
					},
				],
			},
			{
				name: "Above 32 Inches",
				description: [
					{
						name: "Service",
						price: "300",
						imgSrc: "/assests/LED.png",
					},
					{
						name: "Repair",
						price: "500",
						imgSrc: "/assests/led1.jpg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "700",
						imgSrc: "/assests/led2.jpg",
					},
					{
						name: "Uninstallation",
						price: "300",
						imgSrc: "/assests/led4.jpg",
					},
				],
			},
		],
	},
	{
		id: 5,
		type: "Appliance",
		split: false,
		description:
			"Comprehensive refrigerator service offering expert repair and maintenance solutions for optimal cooling and preservation of food freshness.",

		name: "Refrigerator",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "All Types of Refrigerator",
				description: [
					{
						name: "Service",
						price: "500",
						imgSrc: "/assests/r1.jpg",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/r2.jpg",
						extra: "Excluding Spare Parts",
					},
				],
			},
		],
	},
	{
		id: 6,
		type: "Appliance",
		split: false,
		description:
			"Efficient water cooler service providing repair, installation, and Uninstallation solutions for uninterrupted hydration and refreshment.",

		name: "Water Cooler",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "All Types of Water Coolers",
				description: [
					{
						name: "Service",
						price: "500",
						imgSrc: "/assests/wc1.png",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/wc2.jpg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "600",
						imgSrc: "/assests/wc3.jpg",
					},
					{
						name: "Uninstallation",
						price: "300",
						imgSrc: "/assests/wc4.jpg",
					},
				],
			},
		],
	},
	{
		id: 7,
		type: "Appliance",
		split: false,
		description:
			"Complete microwave service offering expert repair, installation, and Uninstallation for convenient cooking and heating solutions.",

		name: "Microwave",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "All Types of Microwave",
				description: [
					{
						name: "Service",
						price: "300",
						imgSrc: "/assests/micro1.jpg",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/micro2.jpg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "300",
						imgSrc: "/assests/micro3.jpg",
					},
					{
						name: "Uninstallation",
						price: "200",
						imgSrc: "/assests/micro4.jpg",
					},
				],
			},
		],
	},
	{
		id: 8,
		type: "Appliance",
		split: false,
		description:
			"Comprehensive deep freezer service providing expert repair, installation, and Uninstallation for reliable preservation of perishables.",
		name: "Deep Freezer",
		conditions: [
			"Mentioned prices are service charges only.",
			"Consumables and spare parts (if used) will be charged extra",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Technicians. All warranty and service assurance in such cases stand null and void.",
			"Our Technicians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Technicians might take the appliance to workshop. if required, with a receiving on email.",
			"Our Technicians might make a revisit, if required, for consumables or spare parts.",
			"Cooling of the appliance depends on multiple factors such as quality of the gas-filled, age, pressure of the gas etc. and only servicing does not guarantee improvement in the cooling.",
			"Appropriate and feasible location is required for all kind of appliance installation. Core-cutting charges will be extra (if required).",
			"Urban Door does not provide any warranty on appliances that are too old or in un-repairable condition. Also, Technician might deny the work after inspection.",
			"Urban Door will not be responsible for any physical damage, or missing parts of the appliance that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the Technician but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when Technician is in your premises. Advise you to keep such items in a safe and secure place and supervise the Technician during service.",
		],
		splitArray: [
			{
				name: "All Types of Deep Freezer",
				description: [
					{
						name: "Service",
						price: "500",
						imgSrc: "/assests/freezer1.jpg",
					},
					{
						name: "Repair",
						price: "300",
						imgSrc: "/assests/freezer2.jpeg",
						extra: "Excluding Spare Parts",
					},
					{
						name: "Installation",
						price: "300",
						imgSrc: "/assests/freezer3.jpg",
					},
					{
						name: "Uninstallation",
						price: "200",
						imgSrc: "/assests/freezer4.jpg",
					},
				],
			},
		],
	},
	{
		id: 9,
		type: "Others",
		split: false,
		name: "Plumbing",

		description:
			"Complete plumbing service: repair, installation, and maintenance for all fixtures – taps, sinks, toilets, and more, ensuring optimal functionality.",
		conditions: [
			"Mentioned prices are inspection charges only.",
			"Final prices will be given after inspection only.",
			"Consumables and spare parts (if used) will be charged extra.",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Plumbers. All warranty and service assurance in such cases stand null and void.",
			"Our Plumbers do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Plumbers might make a revisit, if required, for consumables or spare parts.",
			"Appropriate and feasible location is required for all kind of installation/repair/replacement.",
			"Urban Door will not be responsible for any physical damage, or missing parts that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the plumber but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when plumber is in your premises. Advise you to keep such items in a safe and secure place and supervise the plumber during service.",
			"If Plumber discover any defect in any part of the premises or the existing installation which makes it impracticable or inexpedient to continue with the authorised work, shall, at their sole discretion, conduct repairs deemed necessary to continue with the work. If customer do not allow that repair than Urban door would not be responsible for that work.",
		],
		splitArray: [
			{
				name: "All Types of Plumbing Services - Repair/Installation/Uninstallation/Replacement",
				description: [
					{
						name: "WashBasin",
						price: "300",
						imgSrc: "/assests/wash1.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Sink",
						price: "300",
						imgSrc: "/assests/sink.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Tap & Mixer",
						price: "300",
						imgSrc: "/assests/tab.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Bath Fitting",
						price: "300",
						imgSrc: "/assests/bath.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Toilet",
						price: "300",
						imgSrc: "/assests/toilet.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Blockage",
						price: "300",
						imgSrc: "/assests/block.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Water Tank",
						price: "300",
						imgSrc: "/assests/water.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Water Motor",
						price: "300",
						imgSrc: "/assests/motor.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Other Works",
						price: "300",
						imgSrc: "/assests/other.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "New Fittings",
						price: "300",
						imgSrc: "/assests/fiting.jpg",
						extra: "Final Price after inspection",
					},
				],
			},
		],
	},

	{
		id: 10,
		type: "Others",
		split: false,
		description:
			"Expert carpentry service: doors, windows, furniture, and more - quality craftsmanship guaranteed.",

		name: "Carpentry",
		conditions: [
			"Mentioned prices are inspection charges only.",
			"Final prices will be given after inspection only.",
			"Consumables and spare parts (if used) will be charged extra.",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our carpenters. All warranty and service assurance in such cases stand null and void.",
			"Our carpenters do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our carpenters might make a revisit, if required, for consumables or spare parts.",
			"Appropriate and feasible location is required for all kind of installation/repair/replacement.",
			"Urban Door will not be responsible for any physical damage, or missing parts that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the plumber but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when carpenter is in your premises. Advise you to keep such items in a safe and secure place and supervise the plumber during service.",
			"If carpenter discover any defect in any part of the premises or the existing installation which makes it impracticable or inexpedient to continue with the authorised work, shall, at their sole discretion, conduct repairs deemed necessary to continue with the work. If customer do not allow that repair than Urban door would not be responsible for that work.",
		],
		splitArray: [
			{
				name: "All Types of Carpentry Services - Repair/Installation/Uninstallation/Replacement",
				description: [
					{
						name: "Wooden Door",
						price: "300",
						imgSrc: "/assests/door.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Wooden Window",
						price: "300",
						imgSrc: "/assests/window.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Drill & Hang",
						price: "300",
						imgSrc: "/assests/drill.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Bed",
						price: "300",
						imgSrc: "/assests/bed.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Chair",
						price: "300",
						imgSrc: "/assests/chair.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Table",
						price: "300",
						imgSrc: "/assests/table.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Sofa",
						price: "300",
						imgSrc: "/assests/sofa.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Cupboard & Wardrobe",
						price: "300",
						imgSrc: "/assests/wardrobe.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Drawer",
						price: "300",
						imgSrc: "/assests/drawer.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "ShoeRack",
						price: "300",
						imgSrc: "/assests/shoe.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Book shelf",
						price: "300",
						imgSrc: "/assests/book.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "New Fittings",
						price: "300",
						imgSrc: "/assests/new.jpg",
						extra: "Final Price after inspection",
					},
				],
			},
		],
	},

	{
		id: 11,
		type: "Others",
		split: false,
		description:
			"Comprehensive electrical service covering switches, sockets, lights, MCBs, earthing, tripping, new wiring, and more, ensuring safety and efficiency in every installation and repair.",

		name: "Electrical",
		conditions: [
			"Mentioned prices are inspection charges only.",
			"Final prices will be given after inspection only.",
			"Consumables and spare parts (if used) will be charged extra.",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Electricians. All warranty and service assurance in such cases stand null and void.",
			"Our Electricians do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Electricians might make a revisit, if required, for consumables or spare parts.",
			"Appropriate and feasible location is required for all kind of installation/repair/replacement.",
			"Urban Door will not be responsible for any physical damage, or missing parts that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the plumber but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when electricisn is in your premises. Advise you to keep such items in a safe and secure place and supervise the plumber during service.",
			"If Electrician discover any defect in any part of the premises or the existing installation which makes it impracticable or inexpedient to continue with the authorised work, shall, at their sole discretion, conduct repairs deemed necessary to continue with the work. If customer do not allow that repair than Urban door would not be responsible for that work.",
		],
		splitArray: [
			{
				name: "All Types of Electrical Services - Repair/Installation/Uninstallation/Replacement",
				description: [
					{
						name: "Switch & Socket",
						price: "300",
						imgSrc: "/assests/switch.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Light & holder",
						price: "300",
						imgSrc: "/assests/light.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "MCB & Fuse",
						price: "300",
						imgSrc: "/assests/mcb.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Drill & Hang",
						price: "300",
						imgSrc: "/assests/hang.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Electrical Point",
						price: "300",
						imgSrc: "/assests/point.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Earthing",
						price: "300",
						imgSrc: "/assests/earthing.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Tripping",
						price: "300",
						imgSrc: "/assests/tripling.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "New Wiring",
						price: "300",
						imgSrc: "/assests/wiring.jpg",
						extra: "Final Price after inspection",
					},
				],
			},
		],
	},
	{
		id: 12,
		type: "Others",
		split: false,
		description:
			"Complete pest control service targeting general pests, cockroaches, bed bugs, dengue, ants, lizards, termites, rodents, and more, ensuring comprehensive eradication and prevention.",

		name: "Pest Control",
		conditions: [
			"Mentioned prices are inspection charges only.",
			"Final prices will be given after inspection only.",
			"Consumables and spare parts (if used) will be charged extra.",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Pest Controller. All warranty and service assurance in such cases stand null and void.",
			"Our Pest Controller do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Pest Controller might make a revisit, if required, for consumables or spare parts.",
			"Appropriate and feasible location is required for all kind of installation/repair/replacement.",
			"People sensitive to pesticides must keep away during pest control.",
			"Keep food items in the refrigerator or sealed container.",
			"Do not clean treated surface before it is dried.",
			"Urban Door will not be responsible for any physical damage, or missing parts that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the plumber but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when pest controller is in your premises. Advise you to keep such items in a safe and secure place and supervise the plumber during service.",
			"If Pest controller discover any defect in any part of the premises or the existing installation which makes it impracticable or inexpedient to continue with the authorised work, shall, at their sole discretion, conduct repairs deemed necessary to continue with the work. If customer do not allow that repair than Urban door would not be responsible for that work.",
		],
		splitArray: [
			{
				name: "All Types of Pest Control Services - Repair/Installation/Uninstallation/Replacement",
				description: [
					{
						name: "General Pest Control",
						price: "300",
						imgSrc: "/assests/pest1.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Cockroach Control",
						price: "300",
						imgSrc: "/assests/cockroach.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Bed bugs",
						price: "300",
						imgSrc: "/assests/bugs.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Dengue Control",
						price: "300",
						imgSrc: "/assests/dengue.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Ant Control",
						price: "300",
						imgSrc: "/assests/ant.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Lizard Control",
						price: "300",
						imgSrc: "/assests/lizard.png",
						extra: "Final Price after inspection",
					},
					{
						name: "Termite Control",
						price: "300",
						imgSrc: "/assests/termite.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Rodent Control",
						price: "300",
						imgSrc: "/assests/rodent.jpeg",
						extra: "Final Price after inspection",
					},
				],
			},
		],
	},

	{
		id: 13,
		type: "Others",
		split: false,
		description:
			"Full-spectrum painting service including house painting, waterproofing, textured painting, enamel painting, wood polishing, stenciling, and repairs for comprehensive aesthetic enhancement",

		name: "Painting",
		conditions: [
			"Mentioned prices are inspection charges only.",
			"Final prices will be given after inspection only.",
			"Consumables and spare parts (if used) will be charged extra.",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Painters. All warranty and service assurance in such cases stand null and void.",
			"Our Painters do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Painters might make a revisit, if required, for consumables or spare parts.",
			"Appropriate and feasible location is required for all kind of installation/repair/replacement.",
			"People sensitive to chemical paints must keep away during painting.",
			"Urban Door will not be responsible for any physical damage, or missing parts that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the plumber but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when painter is in your premises. Advise you to keep such items in a safe and secure place and supervise the plumber during service.",
			"If Painter discover any defect in any part of the premises or the existing installation which makes it impracticable or inexpedient to continue with the authorised work, shall, at their sole discretion, conduct repairs deemed necessary to continue with the work. If customer do not allow that repair than Urban door would not be responsible for that work.",
		],
		splitArray: [
			{
				name: "All Types of Painting Services - Repair/Installation/Uninstallation/Replacement",
				description: [
					{
						name: "House Painting",
						price: "300",
						imgSrc: "/assests/house.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "water Proofing",
						price: "300",
						imgSrc: "/assests/water1.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Textured Walls",
						price: "300",
						imgSrc: "/assests/wall1.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Enamel Painting",
						price: "300",
						imgSrc: "/assests/enamel.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Wood Polishing",
						price: "300",
						imgSrc: "/assests/wood1.jpeg",
						extra: "Final Price after inspection",
					},
					{
						name: "Stencil",
						price: "300",
						imgSrc: "/assests/stencil.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Other Repairs",
						price: "300",
						imgSrc: "/assests/paint.jpg",
						extra: "Final Price after inspection",
					},
				],
			},
		],
	},

	{
		id: 14,
		type: "Others",
		split: false,
		description:
			"Comprehensive interior design service transforming kitchens, almirahs, LED panels, wood furniture, and more, for personalized and functional spaces.",

		name: "Interior Designing",
		conditions: [
			"Mentioned prices are inspection charges only.",
			"Final prices will be given after inspection only.",
			"Consumables and spare parts (if used) will be charged extra.",
			"Warranty on consumables and spare parts will be as per manufacturer only.",
			"Urban door provides a 90 day work warranty.",
			"Urban Door Provide a bill for all kind of work after completion.",
			"For all kind of work, information and prices with work note will be given before proceeding.",
			"Urban Door does not allow direct dealing with our Designers. All warranty and service assurance in such cases stand null and void.",
			"Our Designers do not carry ladders. If required, a ladder has to be provided by the customer during work.",
			"Our Designers might make a revisit, if required, for consumables or spare parts.",
			"Appropriate and feasible location is required for all kind of installation/repair/replacement.",
			"Urban Door will not be responsible for any physical damage, or missing parts that are brought to notice after job completion.",
			"Urban door will not be liable for any pre-existing issues/potential risks reported by the plumber but not handled due to customer refusal to repair the same.",
			"Urban Door will not be responsible for any loss or damage to any valuable or breakable item when designer is in your premises. Advise you to keep such items in a safe and secure place and supervise the plumber during service.",
			"If Designers discover any defect in any part of the premises or the existing installation which makes it impracticable or inexpedient to continue with the authorised work, shall, at their sole discretion, conduct repairs deemed necessary to continue with the work. If customer do not allow that repair than Urban door would not be responsible for that work.",
		],
		splitArray: [
			{
				name: "All Types of Interior Designing Services - Repair/Installation/Uninstallation/Replacement",
				description: [
					{
						name: "Kitchen",
						price: "300",
						imgSrc: "/assests/kitchen.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Almirah",
						price: "300",
						imgSrc: "/assests/almirah.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "LED Panel",
						price: "300",
						imgSrc: "/assests/tv.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Wood Furniture",
						price: "300",
						imgSrc: "/assests/wooden.jpg",
						extra: "Final Price after inspection",
					},
					{
						name: "Other Work",
						price: "300",
						imgSrc: "/assests/work1.jpg",
						extra: "Final Price after inspection",
					},
				],
			},
		],
	},
];
